### ISSUE TITLE
Error:No module named plist

### ISSUE THREAD

**Issue by zhangity** [programmin1/iosTransferGUI#2]
when I click "App Documents/File-sharing"   it shows this . how could I slove it ? By the way Add pdf to ibooks can work nicely.Thank you !

**Comment by programmin1** [comment]
From the readme:
"Python-plist and Python-imobiledevice packages should be installed."
In other words run:
`sudo apt-get install python-plist python-imobiledevice`

Sorry, I should've make the instructions more clear. thanks.

**Comment by zhangity** [comment]
Thank you very much! It worked for fine!
I'm sorry I didn't pay much attention to that sentences, anyway thank you
for your work!
Just the speed is so slow (2M/s)when I'm transforing a video to my iPhone.

Anyway, thanks :-)

2016-04-17 4:28 GMT+08:00 programmin1 notifications@github.com:
