### ISSUE TITLE
GUI Design

### ISSUE THREAD

**Issue by KevDoy** [programmin1/iosTransferGUI#3]
Would you be interested in making it look a little better? I am a designer and would love to come up with a few simple examples and provide all of the graphics to you. Please let me know.

**Comment by programmin1** [comment]
What do you mean? Can you show an example from Glade builder and upload example?

**Comment by KevDoy** [comment]
I'm not very familiar with Glade at this point, but I'll add that to the list of things to familiarize myself with. I can definitely make you a flattened mockup though. Is there any way we can email one another. 

Please email me here: if you're interested, if not respond here and we can find another means to communicate better email at kevdoy.me

**Comment by programmin1** [comment]
Can you attach to this ticket so all interested can give input on this design?

**Comment by KevDoy** [comment]
Sure thing, but I would appreciate if we could talk on email first 😄
